### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by vanessa-cooper** [ObelusFamily/Anythink-Market-s449n#3]
Cool! Now, It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data.
Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by 88Navistar** [comment]
![CleanShot 2022-08-16 at 20 54 39](https://user-images.githubusercontent.com/63985483/185024375-7cd9848d-c64a-4934-95ac-603a33bbb98d.png)
